### ISSUE TITLE
heroku-buildpack-mysql-binaries

### ISSUE THREAD

**Issue by genechuah** [musa11971/dotfiles#2]
Hi there.
Sorry there was no other way to contact you besides opening an Issue here.
Your repo https://github.com/musa11971/heroku-buildpack-mysql-binaries went offline recently. Would you be so kind as to show me how I can put this exact one together in my own repo?
Hard to find documentation or a package that actually works for my setup.
Really appreciate it!

**Comment by musa11971** [comment]
Hi, this was something I adopted/forked. I unfortunately completely forgot what it was used for and how it worked, so I'm not really able to help you further on this one. Hope you figure it out and sorry to disappoint!
